version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8020:8020"
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    ports:
      - "5433:5433"
    env_file:
      - .env
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data:cached