version: '3.8'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8020:8020"
    env_file:
      - .env
    environment:
      DB_HOST: "db"
    command: bash -c "while ! </dev/tcp/db/5432; do sleep 1; done;
      alembic upgrade head;
      uvicorn main:app --host=0.0.0.0 --port=8020;"
    volumes:
      - ./src:/app
    depends_on:
      - db

  db:
    image: "postgres:13.3-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    volumes:
      - rss_db_postgres_data:/var/lib/postgresql/data:cached

volumes:
  rss_db_postgres_data:
