version: '3.8'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "8020:8020"
    env_file:
      - .env
    environment:
      DB_HOST: "db"
    depends_on:
      - db
    entrypoint: ./entrypoint-app.sh

  db:
    image: "postgres:13.3-alpine"
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data:cached