"""empty message

Revision ID: 215d66003277
Revises: 
Create Date: 2021-08-03 12:51:41.231168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '215d66003277'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds',
    sa.Column('guid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('can_updated', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('guid'),
    sa.UniqueConstraint('source_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeds')
    # ### end Alembic commands ###
